
// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class SampleTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@BeforeTest
	public void setUp() {
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterTest
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void sample() {
		// Test name: Sample
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://the-internet.herokuapp.com/");
		// 2 | setWindowSize | 1539x884 |
		driver.manage().window().setSize(new Dimension(1539, 884));
		// 3 | click | linkText=A/B Testing |
		driver.findElement(By.linkText("A/B Testing")).click();
		// 4 | verifyText | css=h3 | A/B Test Control
//		assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("A/B Test Control"));
	}
}
